export const TITLE_ORDER = [
  "King of the Seven Kingdoms",
  "Queen of the Seven Kingdoms",
  "Crown Prince",
  "Prince",
  "Princess",
  "Hand of the King",
  "Lord Commander of the Kingsguard",
  "Master of Coin",
  "Grand Maester",
  "Maester",
  "Lord of Winterfell and Warden of the North",
  "Late Lord of Winterfell and Warden of the North",
  "Lord of Dragonstone",
  "Lord of Storm's End",
  "Lord of Torrentine",
  "Lord of Oldtown",
  "Sworn Brother of the Kingsguard",
  "Former Sworn Brother of the Kingsguard",
  "Knight",
  "Lady Naella Velaryon of Driftmark",
  "Lady Lorenah Dayne of Torrentine",
  "Lady Alysanne Hightower of Oldtown",
  "Lady",
  "Traitor",
];
