"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";
import styles from "@/app/users/[username]/profile.module.css";

type Entry={id:string;author_id:string;body:string;created_at:string;parent_id:string|null};
type Person={username:string;display_name:string;avatar_url:string|null};

export default function ProfileGuestbook({profileId,viewerId,canModerate=false}:{profileId:string;viewerId:string|null;canModerate?:boolean}){
 const db=useMemo(()=>createClient(),[]),lock=useRef(false);
 const [rows,setRows]=useState<Entry[]>([]),[people,setPeople]=useState<Record<string,Person>>({}),[body,setBody]=useState(""),[replyBody,setReplyBody]=useState(""),[replyTo,setReplyTo]=useState<string|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
 useEffect(()=>{let active=true;void(async()=>{const {data,error}=await db.from("profile_guestbook").select("*").eq("profile_id",profileId).order("created_at",{ascending:false}).order("id").limit(200);if(!active)return;if(error){setError("Guestbook could not be loaded.");return;}const entries=data as Entry[],ids=[...new Set(entries.map(row=>row.author_id))],result=ids.length?await db.from("profiles").select("id,username,display_name,avatar_url").in("id",ids):{data:[]};if(active){setRows(entries);setPeople(Object.fromEntries((result.data??[]).map(person=>[person.id,person])));}})();return()=>{active=false};},[db,profileId,revision]);
 async function submit(event:React.FormEvent,parentId:string|null=null){event.preventDefault();const text=(parentId?replyBody:body).trim();if(lock.current||!viewerId||!text)return;lock.current=true;setBusy(true);setError("");try{const {error}=await db.from("profile_guestbook").insert({profile_id:profileId,author_id:viewerId,body:text,parent_id:parentId});if(error)throw error;if(parentId){setReplyBody("");setReplyTo(null);}else setBody("");setRevision(value=>value+1);}catch{setError("Your message could not be saved. Try again.");}finally{lock.current=false;setBusy(false);}}
 async function remove(id:string){const {error}=await db.from("profile_guestbook").delete().eq("id",id);if(error)setError("Could not delete this entry.");else setRevision(value=>value+1);}
 const children=new Map<string,Entry[]>();for(const row of rows){if(row.parent_id)children.set(row.parent_id,[...(children.get(row.parent_id)??[]),row]);}
 const renderEntry=(row:Entry,depth=0):React.ReactNode=>{const person=people[row.author_id];return <div className={depth?styles.guestbookReply:""} key={row.id}><article className={`${styles.activityCard} ${styles.guestbookEntry}`}><div className={styles.guestbookRow}>{person&&<Link className={styles.guestbookAvatar} href={`/users/${person.username}`} aria-label={`${person.display_name} profile`}>{person.avatar_url?<img src={person.avatar_url} alt=""/>:<span>{person.display_name.slice(0,2).toUpperCase()}</span>}</Link>}<div className={styles.guestbookBody}><div className={styles.guestbookMeta}>{person&&<Link href={`/users/${person.username}`}>{person.display_name}</Link>}<small>{new Date(row.created_at).toLocaleDateString("en-GB")}</small></div><p>{row.body}</p><div className={styles.guestbookTools}>{viewerId&&<button className={styles.guestbookDelete} onClick={()=>{setReplyTo(replyTo===row.id?null:row.id);setReplyBody("")}}>Reply</button>}{viewerId&&(viewerId===row.author_id||viewerId===profileId||canModerate)&&<button className={styles.guestbookDelete} onClick={()=>void remove(row.id)}>Delete</button>}</div></div></div></article>{replyTo===row.id&&<form className={styles.inlineReply} onSubmit={event=>void submit(event,row.id)}><textarea autoFocus aria-label="Guestbook reply" required maxLength={500} placeholder={`Reply${person?` to ${person.display_name}`:""}…`} value={replyBody} onChange={event=>setReplyBody(event.target.value)}/><div><span>{replyBody.length}/500</span><button type="button" onClick={()=>setReplyTo(null)}>Cancel</button><button disabled={busy||!replyBody.trim()}>{busy?"Posting…":"Reply"}</button></div></form>}{(children.get(row.id)??[]).map(child=>renderEntry(child,Math.min(depth+1,2)))}</div>;};
 const roots=rows.filter(row=>!row.parent_id||!rows.some(parent=>parent.id===row.parent_id));
 return <section className={styles.friends}><div className={styles.friendHeader}><div><span className={styles.guestbookEyebrow}>Public messages</span><h2>Guestbook</h2></div><small>{rows.length?`${rows.length} entries`:"No entries yet"}</small></div><div className={styles.guestbookList}>{roots.map(row=>renderEntry(row))}</div>
  {viewerId&&viewerId!==profileId&&<form className={styles.guestbookComposer} onSubmit={event=>void submit(event)}><div className={styles.guestbookComposerHead}><div><span className={styles.guestbookEyebrow}>Leave your mark</span><h3>Write in this guestbook</h3></div><span className={styles.guestbookCount}>{body.length}/500</span></div><textarea aria-label="Guestbook message" required maxLength={500} placeholder="Leave a public message…" value={body} onChange={event=>setBody(event.target.value)}/><div className={styles.guestbookComposerFoot}><span>Visible to everyone who visits this profile.</span><button disabled={busy||!body.trim()}>{busy?"Posting…":"Leave message"}</button></div></form>}
  {!viewerId&&<Link className={styles.guestbookSignIn} href="/login">Sign in to leave a message</Link>}{error&&<p className={styles.guestbookError} role="status">{error}</p>}
 </section>;
}
