"use client";
import { useMemo, useState } from "react";
import SearchableSelect from "@/components/SearchableSelect";
import { MAP_LOCATION_NAMES } from "@/data/map/locations";
import { calculateTravel } from "@/lib/travel";
import { ToolHeading, WorkbenchHeader } from "../WorkbenchShell";
import styles from "../workbench.module.css";
const options = MAP_LOCATION_NAMES.map((name) => ({ value: name, label: name }));
const days = (n:number) => n < .5 ? `${Math.max(1,Math.round(n*24))} hours` : `${Math.max(1,Math.round(n))} days`;
export default function RoadsPage(){const[from,setFrom]=useState("");const[to,setTo]=useState("");const result=useMemo(()=>from&&to&&from!==to?calculateTravel(from,to):null,[from,to]);return <main className={styles.page}><WorkbenchHeader title="Roads & Ravens">Estimate passage between known places. A roleplay aid, not gospel.</WorkbenchHeader><article className={`${styles.toolCard} ${styles.singleTool}`}><ToolHeading kind="roads" eyebrow="Distance & passage" title="Roads & Ravens"/><div className={styles.selectGrid}><label><span>From</span><SearchableSelect value={from} onChange={setFrom} options={options} placeholder="Choose a place" searchPlaceholder="Search the map…"/></label><label><span>To</span><SearchableSelect value={to} onChange={setTo} options={options} placeholder="Choose a place" searchPlaceholder="Search the map…"/></label></div>{from===to&&from&&<p className={styles.hint}>Choose two different places.</p>}{result&&<><div className={styles.travelResults}>{[["On foot",days(result.footDays)],["Horseback",`${Math.round(result.horseDays[0])}–${Math.round(result.horseDays[1])} days`],["With an army",`${Math.round(result.armyDays[0])}–${Math.round(result.armyDays[1])} days`],["By sea",days(result.seaDays)],["Dragonback",`${Math.round(result.dragonHours[0])}–${Math.round(result.dragonHours[1])} hours`],["By raven",result.ravenHours<24?`${Math.round(result.ravenHours)} hours`:days(result.ravenHours/24)]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><p className={styles.distanceNote}>≈ {Math.round(result.landMiles)} land miles · ≈ {Math.round(result.seaMiles)} sea miles</p></>}</article></main>}
