const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const community = require('../data/flea-bottom.json');
community.comments = community.comments.filter(c => Date.parse(c.publishedAt) <= Date.now());

(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const base = process.env.GUTTER_TEST_URL || 'http://localhost:3100';
  const memeId = 'gallery-a-feast-for-butchers';
  const reelId = 'gallery-derrin-will-return';
  try {
    for (const viewport of [{ width: 1440, height: 900 }, { width: 390, height: 844 }]) {
      await page.setViewportSize(viewport);
      await page.goto(`${base}/ravens-eye/memes?item=${memeId}`);
      const thread = page.getByRole('region', { name: 'Gallery comments' });
      await thread.locator('article').first().waitFor();
      assert.equal(await thread.locator('article').count(), community.comments.filter((c) => c.entryId === memeId).length);
      assert(await thread.getByRole('list', { name: 'Replies to @gaelord_apologist' }).count());
      const profile = thread.locator('summary').first();
      await profile.click();
      await thread.locator('details[open]').getByText('Fictional regular', { exact: true }).waitFor();
      assert(await profile.evaluate((el) => el.parentElement.open));
      const author = community.users.find((user) => user.id === 'regular-g');
      const authorComments = community.comments.filter((comment) => comment.authorId === author.id);
      const authorPosts = new Set(authorComments.map((comment) => comment.entryId)).size;
      const profilePanel = thread.locator('details[open]');
      await profilePanel.getByText(author.displayName, { exact: true }).waitFor();
      await profilePanel.getByText(author.current.value, { exact: true }).waitFor();
      await profilePanel.getByText(`${authorComments.length} comments across ${authorPosts} posts`, { exact: true }).waitFor();
      await profilePanel.getByText(`${author.friendIds.length} ${author.friendIds.length === 1 ? 'friend' : 'friends'}`, { exact: true }).waitFor();
      assert(await profilePanel.evaluate((el) => el.scrollWidth <= el.clientWidth), 'Profile details fit the viewport');
      const footer = thread.getByText(/Member accounts & comments/);
      await footer.scrollIntoViewIfNeeded();
      const footerBounds = await footer.boundingBox();
      assert(footerBounds.y >= 0 && footerBounds.y + footerBounds.height <= viewport.height, 'Thread footer is reachable');
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No horizontal overflow');
      await page.screenshot({ path: `${process.env.TEMP}/gutter-meme-${viewport.width}.png` });
      const original = await thread.locator('article > p').allTextContents();
      await page.reload();
      await thread.locator('article').first().waitFor();
      assert.deepEqual(await thread.locator('article > p').allTextContents(), original, 'Comments persist across reloads');
      await page.getByRole('button', { name: 'Next', exact: true }).click();
      await page.waitForURL((url) => url.searchParams.get('item') !== memeId);
      assert.equal(await page.locator('[class*="gutterLightbox"]').evaluate((el) => el.scrollTop), 0, 'Next meme starts at its image');
      assert(!(await page.locator('details[open]').count()), 'Profile expansion resets for next meme');
      await page.getByRole('button', { name: 'Close', exact: true }).click();
      await thread.waitFor({ state: 'detached' });

      await page.goto(`${base}/ravens-eye/reels?item=${reelId}`);
      const slide = page.locator('[class*="reelSlide"]').filter({ has: page.locator(`video[src="/videos/reels/derrin-will-return.mp4"]`) }).first();
      const talk = slide.getByRole('region', { name: 'Gallery comments' });
      const toggle = talk.getByRole('button', { name: /Gutter talk/ });
      await talk.locator('[id]').first().waitFor({state:'attached'});
      await page.waitForFunction(() => document.querySelector('[aria-label="Gallery comments"][data-ready="true"]'));
      await toggle.click();
      assert.equal(await toggle.getAttribute('aria-expanded'), 'true');
      assert.equal(await talk.locator('article').count(), community.comments.filter((c) => c.entryId === reelId).length);
      await talk.locator('summary').first().click();
      await talk.locator('details[open]').getByText('Fictional regular', { exact: true }).waitFor();
      await talk.getByText(/Member accounts & comments/).scrollIntoViewIfNeeded();
      assert(new URL(page.url()).searchParams.get('item') === reelId, 'Comment scrolling does not change reels');
      await page.screenshot({ path: `${process.env.TEMP}/gutter-reel-${viewport.width}.png` });
      await toggle.click();
      assert.equal(await toggle.getAttribute('aria-expanded'), 'false');
      await page.getByRole('button', { name: 'Close', exact: true }).click();
      await talk.waitFor({ state: 'detached' });
      await page.goto(`${base}/ravens-eye/memes?item=gallery-mslvvyhv`);
      const fandomProfile = page.locator('details').filter({ has: page.locator('summary', { hasText: '@plumbob.sena' }) });
      await fandomProfile.locator('summary').click();
      await fandomProfile.getByText('sena', { exact: true }).waitFor();
      await fandomProfile.getByText('she/her', { exact: true }).waitFor();
      await fandomProfile.getByText('The Sims', { exact: true }).waitFor();
      const fandomComments = community.comments.filter((comment) => comment.authorId === 'regular-fandom-sims');
      const fandomPosts = new Set(fandomComments.map((comment) => comment.entryId)).size;
      await fandomProfile.getByText(`${fandomComments.length} comments across ${fandomPosts} posts`, { exact: true }).waitFor();
      assert(await fandomProfile.evaluate((el) => el.scrollWidth <= el.clientWidth), 'New fandom profile fits the viewport');
      await fandomProfile.scrollIntoViewIfNeeded();
      await page.screenshot({ path: `${process.env.TEMP}/gutter-profile-${viewport.width}.png` });
      await page.getByRole('button', { name: 'Close', exact: true }).click();
      await page.goto(`${base}/ravens-eye/memes?item=gallery-mtlmy3pe`);
      const castThread = page.getByRole('region', { name: 'Gallery comments' });
      const castRoot = castThread.locator('ol').first().locator(':scope > li').first();
      await castRoot.waitFor();
      assert.equal(await castRoot.getAttribute('data-pinned'), 'true');
      assert.equal(await castRoot.getAttribute('data-comment-id'), 'gallery-mtlmy3pe-cast-visit-jacaelon-targaryen');
      assert.equal(await castRoot.getByRole('img', { name: 'Verified character account', exact: true }).count(), 2, 'Both characters retain their badges');
      assert.equal(await castThread.locator('article').count(), community.comments.filter((c) => c.entryId === 'gallery-mtlmy3pe').length, 'Pinning never duplicates comments');
      await castRoot.locator('summary').first().click();
      await castRoot.locator('details[open]').getByText('Age 17 in the chronicle', { exact: false }).waitFor();
      assert.equal(await castRoot.getByRole('link', { name: 'Jacaelon Targaryen', exact: false }).getAttribute('href'), '/characters/jacaelon-targaryen');
      const portrait = castRoot.locator('img').first();
      await portrait.scrollIntoViewIfNeeded();
      await portrait.evaluate(img => img.decode());
      assert((await portrait.getAttribute('src')).includes('jacaelon-targaryen'), 'Character mini portrait loaded');
      await page.screenshot({ path: `${process.env.TEMP}/gutter-cast-${viewport.width}.png` });
      await page.getByRole('button', { name: 'Close', exact: true }).click();
      await page.goto(`${base}/ravens-eye/memes?item=gallery-mri1czah`);
      const replyRoot = page.getByRole('region', { name: 'Gallery comments' }).locator('ol').first().locator(':scope > li').first();
      await replyRoot.waitFor();
      assert.equal(await replyRoot.getAttribute('data-comment-id'), 'gallery-mri1czah-comment-2', 'A character reply promotes its original conversation');
      await replyRoot.getByText('Pinned · Character replied', { exact: true }).waitFor();
      await replyRoot.getByRole('list', { name: 'Replies to @StannisOnFacebook' }).getByText('One glass would have been enough. Thank you.', { exact: true }).waitFor();
      await page.getByRole('button', { name: 'Close', exact: true }).click();
      await page.goto(`${base}/ravens-eye/memes?item=gallery-mri9apme`);
      const institutionRoot = page.locator('[data-comment-id="gallery-mri9apme-institution-citadel"]');
      await institutionRoot.waitFor();
      assert.equal(await institutionRoot.getAttribute('data-pinned'), null, 'Institution accounts do not auto-pin');
      await institutionRoot.getByRole('img', { name: 'Verified institution account' }).waitFor();
      await page.getByRole('button', { name: 'Close', exact: true }).click();
      console.log(`PASS ${viewport.width}px: meme threads, profiles, replies, scroll, persistence, navigation, reel panel`);
    }
    await page.goto(`${base}/ravens-eye?item=gallery-alester-jace-fleabottom`);
    await page.getByRole('button', { name: 'Close', exact: true }).waitFor();
    await page.getByRole('region', { name: 'Gallery comments' }).locator('article').first().waitFor();
    assert.equal(await page.getByRole('region', { name: 'Gallery comments' }).locator('article').count(), 5, 'Canon Raven images have comments');
    for (const viewport of [{width:1440,height:900},{width:390,height:844}]) {
      await page.setViewportSize(viewport);
      await page.goto(`${base}/notifications`);
      await page.getByRole('tab', {name:'Latest comments'}).waitFor();
      const latest = page.locator('[role="tabpanel"] li a').first();
      await latest.waitFor();
      const apiResponse = await page.request.get(`${base}/api/community`);
      assert.match(apiResponse.headers()['cache-control'], /no-store/);
      const published = await apiResponse.json();
      assert.equal(published.comments.length, community.comments.length);
      assert(!JSON.stringify(published).includes('-scheduled-'), 'No pending comments in the response');
      const firstTarget = new URL(await latest.getAttribute('href'), base).searchParams.get('comment');
      await latest.click();
      const focused = page.locator(`[data-comment-id="${firstTarget}"]`);
      await page.waitForFunction(id => document.getElementById(`comment-${id}`)?.dataset.highlighted === 'true', firstTarget);
      assert(await focused.evaluate(el=>document.activeElement===el), 'Feed link focuses exact comment');
      const box = await focused.boundingBox();
      assert(box.y>=0 && box.y < viewport.height, 'Target is visible');
      await page.getByRole('button',{name:'Close',exact:true}).click();
      await page.goto(`${base}/notifications?tab=updates`);
      assert.equal(await page.getByRole('tab',{name:'Update notes'}).getAttribute('aria-selected'),'true');
      await page.getByRole('heading',{name:"Comments across the Raven's Eye"}).waitFor();
      assert.equal(await page.locator('[role="tabpanel"] li').count(),1);
      const bell = page.getByRole('link',{name:'Notifications',exact:true});
      const search = page.getByRole('textbox', {name:'Search the realm'});
      const bellBox = await bell.boundingBox();
      await search.click();
      await page.waitForTimeout(300);
      const searchBox = await search.boundingBox();
      assert(searchBox.x>=0 && searchBox.x+searchBox.width <= bellBox.x, 'Expanded search does not overlap bell');
      assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth), 'Notifications fit mobile');
      await page.screenshot({path:`${process.env.TEMP}/community-notifications-${viewport.width}.png`});
      // Direct links, including a reply, must work without first loading notifications.
      for (const [entryId,route] of [[memeId,'memes'],[reelId,'reels']]) {
        const comment = community.comments.find(c=>c.entryId===entryId && c.parentId) || community.comments.find(c=>c.entryId===entryId);
        await page.goto(`${base}/ravens-eye/${route}?item=${entryId}&comment=${comment.id}#comment-${comment.id}`);
        await page.waitForFunction(id=>document.getElementById(`comment-${id}`)?.dataset.highlighted==='true',comment.id);
        assert.equal(new URL(page.url()).searchParams.get('comment'),comment.id,'Gallery retains exact target');
        assert(await page.locator(`#comment-${comment.id}`).evaluate(el=>el.getBoundingClientRect().top>=0 && el.getBoundingClientRect().top<innerHeight), 'Target reply is on screen');
      }
      console.log(`PASS ${viewport.width}px: notifications, update note, exact comment links, mobile search and portraits`);
    }
    const { publishCommunity } = await import('../lib/communityPublication.mjs');
    const privateData = JSON.parse(require('node:fs').readFileSync(require.resolve('../data/flea-bottom.json'), 'utf8'));
    const scheduled = privateData.comments.find(c=>c.id==='gallery-alester-winterfell-window-scheduled-3');
    let serverClock = Date.parse(scheduled.publishedAt)-1;
    await page.route('**/api/community', route=>route.fulfill({json:publishCommunity(privateData, require('../data/community-updates.json'), serverClock)}));
    await page.goto(`${base}/ravens-eye?item=${scheduled.entryId}&comment=${scheduled.id}`);
    await page.getByText('This comment is not available yet.',{exact:true}).waitFor();
    assert.equal(await page.locator(`[data-comment-id="${scheduled.id}"]`).count(),0);
    serverClock += 1;
    // The ordinary 15-second polling cycle must unfold the scheduled comment without a reload.
    await page.waitForFunction(id=>document.getElementById(`comment-${id}`)?.dataset.highlighted==='true',scheduled.id,{timeout:22000});
    await page.goto(`${base}/notifications`);
    await page.locator('[role="tabpanel"] li a').first().waitFor();
    assert((await page.locator('[role="tabpanel"] li a').first().getAttribute('href')).includes(scheduled.id),'Just-published comment leads notification feed');
    await page.unroute('**/api/community');
    console.log('PASS: scheduled comment unfolds through polling, exact target opens, notification leads feed');
    assert.deepEqual(errors, [], 'No browser errors');
  } finally {
    await browser.close();
  }
})().catch((error) => { console.error(error); process.exitCode = 1; });
