"use client";
import { useEffect, useMemo, useState } from "react";
import RavenIcon from "./RavenIcon";
import styles from "./comment-actions.module.css";

type Target={id:string;title:string;subtitle:string;avatarUrl:string|null;initials:string};
export default function CommentActions({href,body,author,surface}:{href:string;body:string;author:string;surface:"Taverns"|"Raven's Eye"}){
 const [copied,setCopied]=useState(false),[open,setOpen]=useState(false),[targets,setTargets]=useState<Target[]>([]),[selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[status,setStatus]=useState(""),[loading,setLoading]=useState(false),[sending,setSending]=useState(false);
 useEffect(()=>{if(!copied)return;const t=setTimeout(()=>setCopied(false),5000);return()=>clearTimeout(t)},[copied]);
 useEffect(()=>{if(!open)return;setLoading(true);fetch('/api/direct-raven/share-comment').then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p.error||'Raven paths could not be loaded.');setTargets(p.targets||[])}).catch(e=>setStatus(e.message)).finally(()=>setLoading(false))},[open]);
 const visible=useMemo(()=>{const q=query.toLowerCase().trim();return q?targets.filter(t=>(t.title+' '+t.subtitle).toLowerCase().includes(q)):targets},[query,targets]);
 async function copy(){try{await navigator.clipboard.writeText(new URL(href,window.location.origin).toString());setCopied(true)}catch{setStatus('The link could not be copied.')}}
 async function send(){if(!selected.length)return;setSending(true);setStatus('');try{const r=await fetch('/api/direct-raven/share-comment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({href,body,author,surface,conversationIds:selected,message})});const p=await r.json();if(!r.ok)throw new Error(p.error||'The comment could not be sent.');setStatus('Comment sent by raven.');setTimeout(()=>setOpen(false),650)}catch(e){setStatus(e instanceof Error?e.message:'The comment could not be sent.')}finally{setSending(false)}}
 return <><button type="button" className={`${styles.iconButton} ${copied?styles.copied:''}`} onClick={()=>void copy()} aria-label="Copy permalink" title={copied?'Copied':'Copy permalink'}><svg viewBox="0 0 20 20" aria-hidden="true"><path d="M7.2 12.8 5.5 14.5a3.2 3.2 0 0 1-4.5-4.5l2.8-2.8a3.2 3.2 0 0 1 4.5 0M12.8 7.2l1.7-1.7A3.2 3.2 0 1 1 19 10l-2.8 2.8a3.2 3.2 0 0 1-4.5 0M6.8 13.2l6.4-6.4" fill="none" stroke="currentColor" strokeWidth="1.45" strokeLinecap="round" strokeLinejoin="round"/></svg></button><button type="button" className={styles.iconButton} onClick={()=>setOpen(true)} aria-label="Send comment by Direct Raven" title="Send by Direct Raven"><RavenIcon size={16}/></button>
 {open&&<div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)setOpen(false)}}><aside className={styles.sheet} role="dialog" aria-modal="true"><header><div><span>Direct Raven</span><strong>Send this comment</strong></div><button onClick={()=>setOpen(false)} aria-label="Close"><svg viewBox="0 0 24 24"><path d="m7 7 10 10M17 7 7 17"/></svg></button></header><div className={styles.preview}><RavenIcon size={18}/><div><small>{surface} comment · {author}</small><p>{body}</p></div></div><label className={styles.message}><span>Add a message</span><textarea value={message} onChange={e=>setMessage(e.target.value.slice(0,1200))} rows={2} placeholder="Add a few words to the raven…"/></label><label className={styles.search}><span>Search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search ravens and parleys"/></label><div className={styles.targets}>{loading?<p>Calling the rookery…</p>:visible.map(t=><button key={t.id} className={selected.includes(t.id)?styles.selected:''} onClick={()=>setSelected(s=>s.includes(t.id)?s.filter(x=>x!==t.id):[...s,t.id])}><span className={styles.avatar}>{t.avatarUrl?<img src={t.avatarUrl} alt=""/>:t.initials}</span><span><strong>{t.title}</strong><small>{t.subtitle}</small></span><i>{selected.includes(t.id)?'✓':''}</i></button>)}</div>{status&&<p className={styles.status}>{status}</p>}<footer><button disabled={!selected.length||sending} onClick={()=>void send()}><RavenIcon size={16}/>{sending?'Sending…':'Send'}</button></footer></aside></div>}</>;
}
