"use client";
import { useEffect, useState } from "react";
export type RavenGif={id:string;title:string;url:string};
type Gif=RavenGif;
export default function GiphyPicker({onSelect}:{onSelect:(gif:Gif)=>void}){
 const [query,setQuery]=useState(""),[rows,setRows]=useState<Gif[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!query.trim()){setRows([]);setLoading(false);setError("");return;}const controller=new AbortController();setLoading(true);setError("");const timer=setTimeout(()=>{void (async()=>{try{const response=await fetch(`/api/giphy/search?q=${encodeURIComponent(query)}`,{signal:controller.signal});const result=await response.json();if(!response.ok){if(result?.error==="giphy_not_configured")throw new Error("NOT_CONFIGURED");throw new Error("UNAVAILABLE");}setRows(result.data??[]);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error&&e.message==="NOT_CONFIGURED"?"GIF search needs a GIPHY API key configured on the server.":"GIF search is unavailable. Try again.");}finally{if(!controller.signal.aborted)setLoading(false);}})();},300);return()=>{clearTimeout(timer);controller.abort();};},[query]);
 return <div aria-label="GIPHY search"><a href="https://giphy.com" target="_blank" rel="noreferrer">Powered by GIPHY</a><input type="search" aria-label="Search GIFs" maxLength={50} value={query} placeholder="Search GIFs" onChange={e=>setQuery(e.target.value)}/>{loading&&<p role="status">Searching…</p>}<div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:6,maxHeight:180,overflowY:"auto"}}>{rows.map(g=><button type="button" key={g.id} aria-label={`Select ${g.title||"GIF"}`} onClick={()=>onSelect(g)}><img src={g.url} alt={g.title} style={{width:"100%",height:90,objectFit:"contain"}}/></button>)}</div>{!loading&&query&&!rows.length&&!error&&<p>No GIFs found.</p>}{error&&<p role="status">{error}</p>}</div>;
}
