"use client";
import {useEffect,useState} from "react";
export type RavenGif={id:string;url:string;title:string};
export default function GiphyPicker({onSelect}:{onSelect:(gif:RavenGif)=>void}){
 const [query,setQuery]=useState(''),[rows,setRows]=useState<RavenGif[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const key=process.env.NEXT_PUBLIC_GIPHY_API_KEY;
 useEffect(()=>{if(!key||!query.trim()){setRows([]);setLoading(false);setError('');return;}const controller=new AbortController();setLoading(true);setError('');const timer=setTimeout(()=>{void (async()=>{try{const params=new URLSearchParams({api_key:key,q:query,limit:'24',rating:'pg-13'});const response=await fetch(`https://api.giphy.com/v1/gifs/search?${params}`,{signal:controller.signal});if(!response.ok)throw Error();const result=await response.json();setRows((result.data??[]).map((g:{id:string;title:string;images:{fixed_height:{url:string}}})=>({id:g.id,title:g.title,url:g.images.fixed_height.url})));}catch{if(!controller.signal.aborted)setError('GIF search is unavailable. Try again.');}finally{if(!controller.signal.aborted)setLoading(false);}})();},300);return()=>{clearTimeout(timer);controller.abort();};},[key,query]);
 return <div aria-label="GIPHY search"><a href="https://giphy.com" target="_blank" rel="noreferrer">Powered by GIPHY</a>{key?<><input type="search" aria-label="Search GIFs" maxLength={50} value={query} placeholder="Search GIFs" onChange={e=>setQuery(e.target.value)}/>{loading&&<p role="status">Searching…</p>}<div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:6,maxHeight:180,overflowY:'auto'}}>{rows.map(g=><button type="button" key={g.id} aria-label={`Select ${g.title||'GIF'}`} onClick={()=>onSelect(g)}><img src={g.url} alt={g.title} style={{width:'100%',height:90,objectFit:'contain'}}/></button>)}</div>{!loading&&query&&!rows.length&&!error&&<p>No GIFs found.</p>}</>:<p>GIF search is not configured yet.</p>}{error&&<p role="status">{error}</p>}</div>;
}
