"use client";
import { useState } from "react";
import characters from "@/data/characters/characters.json";
import { ToolHeading } from "../WorkbenchShell";
import styles from "../workbench.module.css";
type Thread={id:string;title:string;description:string;status:"Open"|"Dormant"|"Resolved";character_ids:string[];chapter_refs:string[];date_opened:string;latest_development:string;private_gm_context?:string|null};
type ThreadDraft=Omit<Thread,"id">;
const blank=():ThreadDraft=>({title:"",description:"",status:"Open",character_ids:[],chapter_refs:[],date_opened:new Date().toISOString().slice(0,10),latest_development:"",private_gm_context:""});

function Plus(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>}

export default function OpenThreadsClient({initial,isAdmin}:{initial:Thread[];isAdmin:boolean}){
  const[items,setItems]=useState(initial); const[editing,setEditing]=useState<Thread|ThreadDraft|null>(null); const[busy,setBusy]=useState(false); const[message,setMessage]=useState("");
  const names=new Map(characters.map(c=>[c.id,c.name]));
  const request=async(method:"POST"|"PATCH"|"DELETE",body:unknown)=>{const response=await fetch("/api/workbench/threads",{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||"The thread could not be sealed.");return data};
  const save=async()=>{if(!editing)return;setBusy(true);setMessage("");try{const existing="id" in editing;const next=await request(existing?"PATCH":"POST",editing) as Thread;setItems(current=>existing?current.map(x=>x.id===next.id?next:x):[next,...current]);setEditing(null);setMessage(existing?"Changes sealed.":"Thread added.")}catch(error){setMessage(error instanceof Error?error.message:"The thread could not be sealed.")}finally{setBusy(false)}};
  const changeStatus=async(thread:Thread)=>{setBusy(true);setMessage("");try{const next=await request("PATCH",{id:thread.id,status:thread.status==="Resolved"?"Open":"Resolved"}) as Thread;setItems(current=>current.map(x=>x.id===next.id?next:x));setMessage(next.status==="Resolved"?"Thread resolved.":"Thread reopened.")}catch(error){setMessage(error instanceof Error?error.message:"The thread could not be changed.")}finally{setBusy(false)}};
  const remove=async(id:string)=>{if(!confirm("Delete this thread?"))return;setBusy(true);try{await request("DELETE",{id});setItems(x=>x.filter(t=>t.id!==id));setMessage("Thread removed.")}catch(error){setMessage(error instanceof Error?error.message:"The thread could not be removed.")}finally{setBusy(false)}};
  return <article className={`${styles.toolCard} ${styles.singleTool}`}><ToolHeading kind="threads" eyebrow="Story continuity" title="Open Threads"/>
    {isAdmin&&<div className={styles.threadEditBar}><div><strong>Continuity ledger</strong><span>Only authorized admins can alter these story records.</span></div><button type="button" disabled={busy||editing!==null} onClick={()=>{setEditing(blank());setMessage("")}}><Plus/>New entry</button></div>}
    {message&&<p className={styles.saveMessage} role="status">{message}</p>}
    {editing&&<div className={styles.threadForm}><label><span>Title</span><input value={editing.title} maxLength={120} onChange={e=>setEditing({...editing,title:e.target.value})}/></label><label><span>Short description</span><textarea value={editing.description} maxLength={500} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><div className={styles.formGrid}><label><span>Status</span><select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Thread["status"]})}><option>Open</option><option>Dormant</option><option>Resolved</option></select></label><label><span>Date opened</span><input type="date" value={editing.date_opened} onChange={e=>setEditing({...editing,date_opened:e.target.value})}/></label></div><label><span>Related character IDs</span><input value={editing.character_ids.join(", ")} onChange={e=>setEditing({...editing,character_ids:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label><span>Chapters / events</span><input value={editing.chapter_refs.join(", ")} onChange={e=>setEditing({...editing,chapter_refs:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})}/></label><label><span>Latest development</span><textarea value={editing.latest_development} onChange={e=>setEditing({...editing,latest_development:e.target.value})}/></label><label><span>Private GM context</span><textarea value={editing.private_gm_context??""} onChange={e=>setEditing({...editing,private_gm_context:e.target.value})}/></label><div className={styles.formActions}><button className={styles.primary} disabled={busy||!editing.title.trim()} onClick={()=>void save()}>{busy?"Sealing…":"Seal entry"}</button><button className={styles.smallButton} onClick={()=>setEditing(null)}>Cancel</button></div></div>}
    <div className={styles.threadList}>{items.length===0&&<p className={styles.empty}>No continuity threads have been recorded yet.</p>}{items.map(thread=><section className={styles.threadCard} key={thread.id}><div className={styles.threadTop}><span data-status={thread.status}>{thread.status}</span><time>{thread.date_opened}</time></div><h3>{thread.title}</h3><p>{thread.description}</p>{thread.latest_development&&<div className={styles.development}><small>Latest development</small>{thread.latest_development}</div>}<div className={styles.entityLinks}>{thread.character_ids.map(id=><a key={id} href={`/characters/${id}`}>{names.get(id)??id}</a>)}{thread.chapter_refs.map(ref=><a key={ref} href={`/chapters/${ref}`}>{ref.replaceAll("-"," ")}</a>)}</div>{isAdmin&&thread.private_gm_context&&<details className={styles.gmContext}><summary>Private GM context</summary><p>{thread.private_gm_context}</p></details>}{isAdmin&&<div className={styles.cardActions}><button onClick={()=>setEditing(thread)}>Edit</button><button disabled={busy} onClick={()=>void changeStatus(thread)}>{thread.status==="Resolved"?"Reopen":"Resolve"}</button><button disabled={busy} onClick={()=>void remove(thread.id)}>Delete</button></div>}</section>)}</div>
  </article>;
}
