begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('thread','community-xix-malaenar-witness','/forum?thread=community-xix-malaenar-witness','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('thread','community-xix-gods-spoken','/forum?thread=community-xix-gods-spoken','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('thread','community-xix-where-is-nymos','/forum?thread=community-xix-where-is-nymos','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-malaenar-c01','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c01','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c02','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c02','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c03','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c03','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c04','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c04','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c05','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c05','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c06','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c06','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c07','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c07','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c08','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c08','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c09','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c09','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c10','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c10','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c11','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c11','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-malaenar-c12','/forum?thread=community-xix-malaenar-witness&comment=xix-malaenar-c12','community-xix-malaenar-witness','Baelenys did nothing—and the chapter refuses to let him forget it'),
  ('post','xix-gods-c01','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c01','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c02','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c02','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c03','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c03','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c04','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c04','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c05','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c05','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c06','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c06','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c07','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c07','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c08','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c08','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c09','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c09','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c10','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c10','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c11','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c11','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-gods-c12','/forum?thread=community-xix-gods-spoken&comment=xix-gods-c12','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','xix-nymos-c01','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c01','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c02','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c02','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c03','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c03','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c04','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c04','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c05','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c05','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c06','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c06','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c07','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c07','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c08','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c08','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c09','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c09','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c10','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c10','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c11','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c11','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','xix-nymos-c12','/forum?thread=community-xix-where-is-nymos&comment=xix-nymos-c12','community-xix-where-is-nymos','Forget the dragon for one minute: where is Nymos?'),
  ('post','ch19-live-jace-alester-release-valve','/forum?thread=chapter-judgment-by-blood&comment=ch19-live-jace-alester-release-valve','chapter-judgment-by-blood','Chapter XIX: Judgment by Blood — Discussion thread'),
  ('post','ch19-live-jace-alester-not-a-plan','/forum?thread=chapter-judgment-by-blood&comment=ch19-live-jace-alester-not-a-plan','chapter-judgment-by-blood','Chapter XIX: Judgment by Blood — Discussion thread')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
