begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-hrrm-ama-ending-plan-defender-reply','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-ending-plan-defender-reply','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-children-pay-hrrm-username-jace-warning','/forum?thread=chapter-the-children-pay&comment=live-children-pay-hrrm-username-jace-warning','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('raven','gallery-rhaella-targaryen-portrait-lurk','/ravens-eye?item=gallery-rhaella-targaryen-portrait&comment=gallery-rhaella-targaryen-portrait-lurk',null,null),
  ('raven','gallery-rhaella-targaryen-portrait-feminist','/ravens-eye?item=gallery-rhaella-targaryen-portrait&comment=gallery-rhaella-targaryen-portrait-feminist',null,null),
  ('raven','gallery-rhaella-targaryen-portrait-club','/ravens-eye?item=gallery-rhaella-targaryen-portrait&comment=gallery-rhaella-targaryen-portrait-club',null,null),
  ('raven','gallery-visenor-rhaella-baby-fic','/ravens-eye?item=gallery-visenor-rhaella-baby&comment=gallery-visenor-rhaella-baby-fic',null,null),
  ('raven','gallery-visenor-rhaella-baby-critic','/ravens-eye?item=gallery-visenor-rhaella-baby&comment=gallery-visenor-rhaella-baby-critic',null,null),
  ('raven','gallery-visenor-rhaella-baby-v','/ravens-eye?item=gallery-visenor-rhaella-baby&comment=gallery-visenor-rhaella-baby-v',null,null),
  ('raven','gallery-visenor-rhaella-baby-optimist','/ravens-eye?item=gallery-visenor-rhaella-baby&comment=gallery-visenor-rhaella-baby-optimist',null,null),
  ('raven','gallery-visenor-rhaella-coronation-legal','/ravens-eye?item=gallery-visenor-rhaella-coronation&comment=gallery-visenor-rhaella-coronation-legal',null,null),
  ('raven','gallery-visenor-rhaella-coronation-naella','/ravens-eye?item=gallery-visenor-rhaella-coronation&comment=gallery-visenor-rhaella-coronation-naella',null,null),
  ('raven','gallery-visenor-rhaella-coronation-fic','/ravens-eye?item=gallery-visenor-rhaella-coronation&comment=gallery-visenor-rhaella-coronation-fic',null,null),
  ('raven','gallery-visenor-rhaella-red-mountains-b','/ravens-eye?item=gallery-visenor-rhaella-red-mountains&comment=gallery-visenor-rhaella-red-mountains-b',null,null),
  ('raven','gallery-visenor-rhaella-red-mountains-v','/ravens-eye?item=gallery-visenor-rhaella-red-mountains&comment=gallery-visenor-rhaella-red-mountains-v',null,null),
  ('raven','gallery-visenor-rhaella-red-mountains-divorced','/ravens-eye?item=gallery-visenor-rhaella-red-mountains&comment=gallery-visenor-rhaella-red-mountains-divorced',null,null),
  ('raven','gallery-life-if-tyrells-didnt-exist-v','/ravens-eye?item=gallery-life-if-tyrells-didnt-exist&comment=gallery-life-if-tyrells-didnt-exist-v',null,null),
  ('raven','gallery-life-if-tyrells-didnt-exist-legal','/ravens-eye?item=gallery-life-if-tyrells-didnt-exist&comment=gallery-life-if-tyrells-didnt-exist-legal',null,null),
  ('raven','gallery-life-if-tyrells-didnt-exist-sport','/ravens-eye?item=gallery-life-if-tyrells-didnt-exist&comment=gallery-life-if-tyrells-didnt-exist-sport',null,null),
  ('raven','gallery-life-if-tyrells-didnt-exist-middle','/ravens-eye?item=gallery-life-if-tyrells-didnt-exist&comment=gallery-life-if-tyrells-didnt-exist-middle',null,null),
  ('raven','gallery-rhaella-geri-don-bilingual','/ravens-eye?item=gallery-rhaella-geri-don&comment=gallery-rhaella-geri-don-bilingual',null,null),
  ('raven','gallery-rhaella-geri-don-club','/ravens-eye?item=gallery-rhaella-geri-don&comment=gallery-rhaella-geri-don-club',null,null),
  ('raven','gallery-rhaella-geri-don-grammar','/ravens-eye?item=gallery-rhaella-geri-don&comment=gallery-rhaella-geri-don-grammar',null,null),
  ('raven','gallery-rhaella-wait-wait-reformed','/ravens-eye?item=gallery-rhaella-wait-wait&comment=gallery-rhaella-wait-wait-reformed',null,null),
  ('raven','gallery-rhaella-wait-wait-wellness','/ravens-eye?item=gallery-rhaella-wait-wait&comment=gallery-rhaella-wait-wait-wellness',null,null),
  ('raven','gallery-visenor-rhaella-another-love-music','/ravens-eye?item=gallery-visenor-rhaella-another-love&comment=gallery-visenor-rhaella-another-love-music',null,null),
  ('raven','gallery-visenor-rhaella-another-love-render','/ravens-eye?item=gallery-visenor-rhaella-another-love&comment=gallery-visenor-rhaella-another-love-render',null,null),
  ('raven','gallery-visenor-rhaella-another-love-lurk','/ravens-eye?item=gallery-visenor-rhaella-another-love&comment=gallery-visenor-rhaella-another-love-lurk',null,null),
  ('raven','gallery-visenor-rhaella-song-before-music','/ravens-eye?item=gallery-visenor-rhaella-someone-wrote-this-song-before&comment=gallery-visenor-rhaella-song-before-music',null,null),
  ('raven','gallery-visenor-rhaella-song-before-quiet','/ravens-eye?item=gallery-visenor-rhaella-someone-wrote-this-song-before&comment=gallery-visenor-rhaella-song-before-quiet',null,null),
  ('raven','gallery-visenor-rhaella-song-before-gate','/ravens-eye?item=gallery-visenor-rhaella-someone-wrote-this-song-before&comment=gallery-visenor-rhaella-song-before-gate',null,null),
  ('raven','gallery-visenor-rhaella-one-away-unship','/ravens-eye?item=gallery-visenor-rhaella-the-one-that-got-away&comment=gallery-visenor-rhaella-one-away-unship',null,null),
  ('raven','gallery-visenor-rhaella-one-away-fic','/ravens-eye?item=gallery-visenor-rhaella-the-one-that-got-away&comment=gallery-visenor-rhaella-one-away-fic',null,null),
  ('raven','gallery-visenor-rhaella-one-away-divorced','/ravens-eye?item=gallery-visenor-rhaella-the-one-that-got-away&comment=gallery-visenor-rhaella-one-away-divorced',null,null),
  ('raven','gallery-whole-westeros-housebreak-g','/ravens-eye?item=gallery-whole-westeros-if-gaelor-housebreak&comment=gallery-whole-westeros-housebreak-g',null,null),
  ('raven','gallery-whole-westeros-housebreak-u','/ravens-eye?item=gallery-whole-westeros-if-gaelor-housebreak&comment=gallery-whole-westeros-housebreak-u',null,null),
  ('raven','gallery-whole-westeros-housebreak-anti','/ravens-eye?item=gallery-whole-westeros-if-gaelor-housebreak&comment=gallery-whole-westeros-housebreak-anti',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
