begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','jace-delay-tail-01','/forum?thread=community-jace-heir-celebration-delay&comment=jace-delay-tail-01','community-jace-heir-celebration-delay','Jace heir ilan edilmeden kutlama yok'),
  ('post','cake-board-tail-01','/forum?thread=community-pocket-cake-evidence-board&comment=cake-board-tail-01','community-pocket-cake-evidence-board','Pocket cake kanıt zinciri: bir kek nasıl tavern meme olur'),
  ('post','gaelor-baby-tail-01','/forum?thread=community-gaelor-canon-baby-factcheck&comment=gaelor-baby-tail-01','community-gaelor-canon-baby-factcheck','Gaelor''un sözde CK3 bebekliği: canon değil ama çok komik'),
  ('post','cursed-raven-tail-01','/forum?thread=community-cursed-raven-anatomy&comment=cursed-raven-tail-01','community-cursed-raven-anatomy','İnsan-kuzgun merge''ü neden bu kadar cursed?'),
  ('post','aenys-dream-tail-01','/forum?thread=community-aenys-dreams-meme-archive&comment=aenys-dream-tail-01','community-aenys-dreams-meme-archive','Have you seen this man in your dreams? Aenys II edition'),
  ('post','canon-meme-tail-01','/forum?thread=meta-flea-bottom-canon-versus-meme&comment=canon-meme-tail-01','meta-flea-bottom-canon-versus-meme','Flea Bottom arşivinde canon, headcanon ve meme sınırı'),
  ('raven','gallery-aenys-ii-bu-adami-ruyanizda-comment-tail','/ravens-eye?item=gallery-aenys-ii-bu-adami-ruyanizda&comment=gallery-aenys-ii-bu-adami-ruyanizda-comment-tail',null,null),
  ('raven','gallery-cursed-raven-comment-tail','/ravens-eye?item=gallery-cursed-raven&comment=gallery-cursed-raven-comment-tail',null,null),
  ('raven','gallery-prince-gaelor-baby-ck3-agot-comment-tail','/ravens-eye?item=gallery-prince-gaelor-baby-ck3-agot&comment=gallery-prince-gaelor-baby-ck3-agot-comment-tail',null,null),
  ('raven','gallery-vhaemys-pocket-cake-comment-tail','/ravens-eye?item=gallery-vhaemys-pocket-cake&comment=gallery-vhaemys-pocket-cake-comment-tail',null,null),
  ('raven','gallery-jace-heir-olunca-comment-tail','/ravens-eye?item=gallery-jace-heir-olunca&comment=gallery-jace-heir-olunca-comment-tail',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
