begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-side-character-pet-vhaemys-rabbit-reply','/forum?thread=community-side-character-pet-draft&comment=live-side-character-pet-vhaemys-rabbit-reply','community-side-character-pet-draft','Draft one animal companion for a side character')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
