begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('raven','live-rhaella-one-away-luck-club','/ravens-eye?item=gallery-visenor-rhaella-the-one-that-got-away&comment=live-rhaella-one-away-luck-club',null,null),
  ('raven','live-rhaella-one-away-ubeka-ashtray','/ravens-eye?item=gallery-visenor-rhaella-the-one-that-got-away&comment=live-rhaella-one-away-ubeka-ashtray',null,null),
  ('raven','live-visenor-cuddle-ubeka-v-reply','/ravens-eye?item=gallery-visenor-rhaella-cuddle-room&comment=live-visenor-cuddle-ubeka-v-reply',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
