begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('raven','gallery-cursed-raven-natural-02','/ravens-eye?item=gallery-cursed-raven&comment=gallery-cursed-raven-natural-02',null,null),
  ('raven','gallery-cursed-raven-natural-06','/ravens-eye?item=gallery-cursed-raven&comment=gallery-cursed-raven-natural-06',null,null),
  ('raven','gallery-cursed-raven-natural-09','/ravens-eye?item=gallery-cursed-raven&comment=gallery-cursed-raven-natural-09',null,null),
  ('raven','gallery-cursed-raven-natural-04','/ravens-eye?item=gallery-cursed-raven&comment=gallery-cursed-raven-natural-04',null,null),
  ('raven','gallery-cursed-raven-natural-05','/ravens-eye?item=gallery-cursed-raven&comment=gallery-cursed-raven-natural-05',null,null),
  ('raven','gallery-cursed-raven-natural-07','/ravens-eye?item=gallery-cursed-raven&comment=gallery-cursed-raven-natural-07',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
