begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-hrrm-ama-not-dbz-powerscaling','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-not-dbz-powerscaling','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-control-room-critic','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-control-room-critic','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('raven','live-jhaella-ubeka-ship-zero-reply','/ravens-eye?item=gallery-jhaella&comment=live-jhaella-ubeka-ship-zero-reply',null,null),
  ('raven','live-jhaella-ubeka-admin-critic-reply','/ravens-eye?item=gallery-jhaella&comment=live-jhaella-ubeka-admin-critic-reply',null,null),
  ('raven','live-visenor-coronation-copium-reply','/ravens-eye?item=gallery-visenor-rhaella-coronation&comment=live-visenor-coronation-copium-reply',null,null),
  ('raven','live-tyrell-soon-bread-reply','/ravens-eye?item=gallery-life-if-tyrells-didnt-exist&comment=live-tyrell-soon-bread-reply',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
