begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('thread','chapter-the-eye-in-the-storm','/forum?thread=chapter-the-eye-in-the-storm','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread'),
  ('post','ch19-live-crowd-majority-clarification','/forum?thread=community-xix-gods-spoken&comment=ch19-live-crowd-majority-clarification','community-xix-gods-spoken','The crowd changing its mind after Gaelor wins is the real horror'),
  ('post','ch20-storm-c01','/forum?thread=chapter-the-eye-in-the-storm&comment=ch20-storm-c01','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread'),
  ('post','ch20-storm-c02','/forum?thread=chapter-the-eye-in-the-storm&comment=ch20-storm-c02','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread'),
  ('post','ch20-storm-c03','/forum?thread=chapter-the-eye-in-the-storm&comment=ch20-storm-c03','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread'),
  ('post','ch20-storm-c04','/forum?thread=chapter-the-eye-in-the-storm&comment=ch20-storm-c04','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread'),
  ('post','ch20-storm-c05','/forum?thread=chapter-the-eye-in-the-storm&comment=ch20-storm-c05','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread'),
  ('post','ch20-storm-c06','/forum?thread=chapter-the-eye-in-the-storm&comment=ch20-storm-c06','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread'),
  ('post','ch20-storm-c07','/forum?thread=chapter-the-eye-in-the-storm&comment=ch20-storm-c07','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread'),
  ('post','ch20-storm-c08','/forum?thread=chapter-the-eye-in-the-storm&comment=ch20-storm-c08','chapter-the-eye-in-the-storm','Chapter XX: The Eye in the Storm — Discussion thread')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
