begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-king18-luck-pocket-cake-poll','/forum?thread=community-chapter-18-who-should-be-king&comment=live-king18-luck-pocket-cake-poll','community-chapter-18-who-should-be-king','As of Chapter XVIII, who should be king—and why?')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
