begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','chapter-the-children-pay-comment-97','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-97','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-98','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-98','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-99','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-99','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-100','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-100','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-101','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-101','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-102','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-102','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-103','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-103','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-104','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-104','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-105','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-105','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-106','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-106','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-107','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-107','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','chapter-the-children-pay-comment-108','/forum?thread=chapter-the-children-pay&comment=chapter-the-children-pay-comment-108','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
