begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('thread','meta-heir-pressure-cooker','/forum?thread=meta-heir-pressure-cooker','meta-heir-pressure-cooker','A secret heir is a pressure cooker, not a coronation'),
  ('thread','community-kingsguard-draft-board','/forum?thread=community-kingsguard-draft-board','community-kingsguard-draft-board','Kingsguard draft board: who actually belongs on the final roster?')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;