begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-hrrm-ama-comprehension-jace-warning','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-comprehension-jace-warning','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('raven','live-visenor-rhaella-kiss-ubeka-v','/ravens-eye?item=gallery-visenor-rhaella-kiss&comment=live-visenor-rhaella-kiss-ubeka-v',null,null),
  ('raven','live-winner-takes-all-luck-music','/ravens-eye?item=gallery-visenor-renrose-winner-takes-it-all&comment=live-winner-takes-all-luck-music',null,null),
  ('raven','live-winner-takes-all-luck-critic','/ravens-eye?item=gallery-visenor-renrose-winner-takes-it-all&comment=live-winner-takes-all-luck-critic',null,null),
  ('raven','live-citadel-death-warrant-archive','/ravens-eye?item=gallery-visenor-entering-citadel-first-time&comment=live-citadel-death-warrant-archive',null,null),
  ('raven','live-rhaella-theme-critic','/ravens-eye?item=gallery-rhaella-ambush&comment=live-rhaella-theme-critic',null,null),
  ('raven','live-alarm-ubeka-finalgirl','/ravens-eye?item=gallery-visenor-rhaella-alarm&comment=live-alarm-ubeka-finalgirl',null,null),
  ('raven','live-queen-never-was-feminist','/ravens-eye?item=gallery-rhaella-boneskin-dracarys&comment=live-queen-never-was-feminist',null,null),
  ('raven','live-gods-cruel-faith','/ravens-eye?item=gallery-rhaella-death-hrrm-baskan-yapma&comment=live-gods-cruel-faith',null,null),
  ('raven','live-hrrm-adadan-correction-local','/ravens-eye?item=gallery-hrrm-adadan-git&comment=live-hrrm-adadan-correction-local',null,null),
  ('raven','live-rhaella-tragic-life-critic','/ravens-eye?item=gallery-visenor-rhaella-boneskin-sad-mcmahon&comment=live-rhaella-tragic-life-critic',null,null),
  ('raven','live-winner-for-now-legal','/ravens-eye?item=gallery-visenor-renrose-winner-takes-it-all&comment=live-winner-for-now-legal',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
