begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-children-pay-justice-legal-reply','/forum?thread=chapter-the-children-pay&comment=live-children-pay-justice-legal-reply','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-hrrm-ama-comprehension-jace-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-comprehension-jace-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('raven','live-visenor-cuddle-father-truth-v','/ravens-eye?item=gallery-visenor-rhaella-cuddle-room&comment=live-visenor-cuddle-father-truth-v',null,null),
  ('raven','live-rhaella-mourn-her-critic-reply','/ravens-eye?item=gallery-visenor-rhaella-boneskin-sad-mcmahon&comment=live-rhaella-mourn-her-critic-reply',null,null),
  ('raven','live-rhaella-stolen-future-feminist-reply','/ravens-eye?item=gallery-rhaella-boneskin-dracarys&comment=live-rhaella-stolen-future-feminist-reply',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
