begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-hrrm-ama-polyphemus-jacejpeg-reply','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-polyphemus-jacejpeg-reply','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-until-last-breath-baelenys-belief-correction','/forum?thread=chapter-until-the-last-breath&comment=live-until-last-breath-baelenys-belief-correction','chapter-until-the-last-breath','Chapter XVIII: Until The Last Breath — Discussion thread'),
  ('post','live-until-last-breath-gaelor-recruitment-refusal','/forum?thread=chapter-until-the-last-breath&comment=live-until-last-breath-gaelor-recruitment-refusal','chapter-until-the-last-breath','Chapter XVIII: Until The Last Breath — Discussion thread')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
