begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','margin-notes-ghost-dragon','/forum?thread=theory-ghost-dragon&comment=margin-notes-ghost-dragon','theory-ghost-dragon','Ghost dragon theories: camouflage is not invisibility'),
  ('post','margin-notes-starfall','/forum?thread=theory-starfall-evidence&comment=margin-notes-starfall','theory-starfall-evidence','Starfall: what we know, what we are guessing'),
  ('post','margin-notes-white-dragon','/forum?thread=theory-white-dragon-dream&comment=margin-notes-white-dragon','theory-white-dragon-dream','Vhaemys, Ghost, and the white dragon: evidence board'),
  ('post','margin-notes-heir-pressure','/forum?thread=meta-heir-pressure-cooker&comment=margin-notes-heir-pressure','meta-heir-pressure-cooker','A secret heir is a pressure cooker, not a coronation'),
  ('post','margin-notes-dragon-ranking','/forum?thread=community-dragon-ranking-fatigue&comment=margin-notes-dragon-ranking','community-dragon-ranking-fatigue','Can we have one dragon thread without making a tier list?')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
