begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('raven','gallery-jhaella-impossible-wedding','/ravens-eye?item=gallery-jhaella&comment=gallery-jhaella-impossible-wedding',null,null),
  ('raven','gallery-jhaella-two-frames-evidence','/ravens-eye?item=gallery-jhaella&comment=gallery-jhaella-two-frames-evidence',null,null),
  ('raven','gallery-jhaella-dorne-objection','/ravens-eye?item=gallery-jhaella&comment=gallery-jhaella-dorne-objection',null,null),
  ('raven','gallery-jhaella-impossible-hostile-witness','/ravens-eye?item=gallery-jhaella&comment=gallery-jhaella-impossible-hostile-witness',null,null),
  ('raven','gallery-jhaella-unship-excellent','/ravens-eye?item=gallery-jhaella&comment=gallery-jhaella-unship-excellent',null,null),
  ('raven','gallery-jhaella-fic-epilogue','/ravens-eye?item=gallery-jhaella&comment=gallery-jhaella-fic-epilogue',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
