begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-pocket-cake-luck-food-20260916','/forum?thread=community-chapter-18-who-should-be-king&comment=live-pocket-cake-luck-food-20260916','community-chapter-18-who-should-be-king','As of Chapter XVIII, who should be king—and why?'),
  ('raven','sep16-jace-heir-01','/ravens-eye?item=gallery-jace-heir-olunca&comment=sep16-jace-heir-01',null,null),
  ('raven','sep16-jace-heir-02','/ravens-eye?item=gallery-jace-heir-olunca&comment=sep16-jace-heir-02',null,null),
  ('raven','sep16-pocket-01','/ravens-eye?item=gallery-vhaemys-pocket-cake&comment=sep16-pocket-01',null,null),
  ('raven','sep16-pocket-02','/ravens-eye?item=gallery-vhaemys-pocket-cake&comment=sep16-pocket-02',null,null),
  ('raven','sep16-baby-01','/ravens-eye?item=gallery-prince-gaelor-baby-ck3-agot&comment=sep16-baby-01',null,null),
  ('raven','sep16-baby-02','/ravens-eye?item=gallery-prince-gaelor-baby-ck3-agot&comment=sep16-baby-02',null,null),
  ('raven','sep16-raven-01','/ravens-eye?item=gallery-cursed-kuzgun&comment=sep16-raven-01',null,null),
  ('raven','sep16-raven-02','/ravens-eye?item=gallery-cursed-kuzgun&comment=sep16-raven-02',null,null),
  ('raven','sep16-aenys-01','/ravens-eye?item=gallery-aenys-ii-bu-adami-ruyanizda&comment=sep16-aenys-01',null,null),
  ('raven','sep16-aenys-02','/ravens-eye?item=gallery-aenys-ii-bu-adami-ruyanizda&comment=sep16-aenys-02',null,null),
  ('raven','sep16-gallery-scheduled-01','/ravens-eye?item=gallery-jace-heir-olunca&comment=sep16-gallery-scheduled-01',null,null),
  ('raven','sep16-gallery-scheduled-02','/ravens-eye?item=gallery-vhaemys-pocket-cake&comment=sep16-gallery-scheduled-02',null,null),
  ('raven','sep16-gallery-scheduled-03','/ravens-eye?item=gallery-prince-gaelor-baby-ck3-agot&comment=sep16-gallery-scheduled-03',null,null),
  ('raven','sep16-gallery-scheduled-04','/ravens-eye?item=gallery-cursed-kuzgun&comment=sep16-gallery-scheduled-04',null,null),
  ('raven','sep16-gallery-scheduled-05','/ravens-eye?item=gallery-aenys-ii-bu-adami-ruyanizda&comment=sep16-gallery-scheduled-05',null,null),
  ('raven','sep16-gallery-scheduled-06','/ravens-eye?item=gallery-jace-heir-olunca&comment=sep16-gallery-scheduled-06',null,null),
  ('raven','sep16-gallery-scheduled-07','/ravens-eye?item=gallery-vhaemys-pocket-cake&comment=sep16-gallery-scheduled-07',null,null),
  ('raven','sep16-gallery-scheduled-08','/ravens-eye?item=gallery-prince-gaelor-baby-ck3-agot&comment=sep16-gallery-scheduled-08',null,null),
  ('raven','sep16-gallery-scheduled-09','/ravens-eye?item=gallery-cursed-kuzgun&comment=sep16-gallery-scheduled-09',null,null),
  ('raven','sep16-gallery-scheduled-10','/ravens-eye?item=gallery-aenys-ii-bu-adami-ruyanizda&comment=sep16-gallery-scheduled-10',null,null),
  ('raven','sep16-gallery-scheduled-11','/ravens-eye?item=gallery-jace-heir-olunca&comment=sep16-gallery-scheduled-11',null,null),
  ('raven','sep16-gallery-scheduled-12','/ravens-eye?item=gallery-vhaemys-pocket-cake&comment=sep16-gallery-scheduled-12',null,null),
  ('raven','sep16-gallery-scheduled-13','/ravens-eye?item=gallery-prince-gaelor-baby-ck3-agot&comment=sep16-gallery-scheduled-13',null,null),
  ('raven','sep16-gallery-scheduled-14','/ravens-eye?item=gallery-cursed-kuzgun&comment=sep16-gallery-scheduled-14',null,null),
  ('raven','sep16-gallery-scheduled-15','/ravens-eye?item=gallery-aenys-ii-bu-adami-ruyanizda&comment=sep16-gallery-scheduled-15',null,null),
  ('raven','sep16-gallery-scheduled-16','/ravens-eye?item=gallery-jace-heir-olunca&comment=sep16-gallery-scheduled-16',null,null),
  ('raven','sep16-gallery-scheduled-17','/ravens-eye?item=gallery-vhaemys-pocket-cake&comment=sep16-gallery-scheduled-17',null,null),
  ('raven','sep16-gallery-scheduled-18','/ravens-eye?item=gallery-prince-gaelor-baby-ck3-agot&comment=sep16-gallery-scheduled-18',null,null),
  ('raven','sep16-gallery-scheduled-19','/ravens-eye?item=gallery-cursed-kuzgun&comment=sep16-gallery-scheduled-19',null,null),
  ('raven','sep16-gallery-scheduled-20','/ravens-eye?item=gallery-aenys-ii-bu-adami-ruyanizda&comment=sep16-gallery-scheduled-20',null,null),
  ('raven','sep16-gallery-scheduled-21','/ravens-eye?item=gallery-jace-heir-olunca&comment=sep16-gallery-scheduled-21',null,null),
  ('raven','sep16-gallery-scheduled-22','/ravens-eye?item=gallery-vhaemys-pocket-cake&comment=sep16-gallery-scheduled-22',null,null),
  ('raven','sep16-gallery-scheduled-23','/ravens-eye?item=gallery-prince-gaelor-baby-ck3-agot&comment=sep16-gallery-scheduled-23',null,null),
  ('raven','sep16-gallery-scheduled-24','/ravens-eye?item=gallery-cursed-kuzgun&comment=sep16-gallery-scheduled-24',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
