begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('raven','almar-renrose-citation','/ravens-eye?item=gallery-almar-and-renrose&comment=almar-renrose-citation',null,null),
  ('raven','almar-renrose-career','/ravens-eye?item=gallery-almar-and-renrose&comment=almar-renrose-career',null,null),
  ('raven','almar-renrose-legal','/ravens-eye?item=gallery-almar-and-renrose&comment=almar-renrose-legal',null,null),
  ('raven','renrose-breakfast-food','/ravens-eye?item=gallery-renrose-gardens-breakfast&comment=renrose-breakfast-food',null,null),
  ('raven','renrose-breakfast-local','/ravens-eye?item=gallery-renrose-gardens-breakfast&comment=renrose-breakfast-local',null,null),
  ('raven','renrose-rose-optimist','/ravens-eye?item=gallery-renrose-rose-gardens&comment=renrose-rose-optimist',null,null),
  ('raven','renrose-rose-u','/ravens-eye?item=gallery-renrose-rose-gardens&comment=renrose-rose-u',null,null),
  ('raven','renrose-desk-ledger','/ravens-eye?item=gallery-renrose-work-desk&comment=renrose-desk-ledger',null,null),
  ('raven','renrose-desk-grad','/ravens-eye?item=gallery-renrose-work-desk&comment=renrose-desk-grad',null,null),
  ('raven','gaelor-teror-g','/ravens-eye?item=gallery-gaelor-teror-orgutu-lideri&comment=gaelor-teror-g',null,null),
  ('raven','gaelor-teror-e','/ravens-eye?item=gallery-gaelor-teror-orgutu-lideri&comment=gaelor-teror-e',null,null),
  ('raven','gaelor-teror-watch','/ravens-eye?item=gallery-gaelor-teror-orgutu-lideri&comment=gaelor-teror-watch',null,null),
  ('raven','gaelor-teror-scheduled-cast','/ravens-eye?item=gallery-gaelor-teror-orgutu-lideri&comment=gaelor-teror-scheduled-cast',null,null),
  ('raven','uclu-m','/ravens-eye?item=gallery-jace-gaelor-visenor-bu-uclu-cok-guclu&comment=uclu-m',null,null),
  ('raven','uclu-gym','/ravens-eye?item=gallery-jace-gaelor-visenor-bu-uclu-cok-guclu&comment=uclu-gym',null,null),
  ('raven','uclu-v','/ravens-eye?item=gallery-jace-gaelor-visenor-bu-uclu-cok-guclu&comment=uclu-v',null,null),
  ('raven','uclu-scheduled-j','/ravens-eye?item=gallery-jace-gaelor-visenor-bu-uclu-cok-guclu&comment=uclu-scheduled-j',null,null),
  ('raven','lorent-ideas-grad','/ravens-eye?item=gallery-lorent-renrose-a-man-will-die-but-not-his-ideas&comment=lorent-ideas-grad',null,null),
  ('raven','lorent-ideas-club','/ravens-eye?item=gallery-lorent-renrose-a-man-will-die-but-not-his-ideas&comment=lorent-ideas-club',null,null),
  ('raven','lorent-ideas-u','/ravens-eye?item=gallery-lorent-renrose-a-man-will-die-but-not-his-ideas&comment=lorent-ideas-u',null,null),
  ('raven','lorent-ideas-scheduled-l','/ravens-eye?item=gallery-lorent-renrose-a-man-will-die-but-not-his-ideas&comment=lorent-ideas-scheduled-l',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
