begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-hrrm-ama-blindside-moderation-2','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-blindside-moderation-2','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-blindside-moderation-3','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-blindside-moderation-3','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-blindside-moderation-4','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-blindside-moderation-4','c774865d-28f3-4cd5-abc0-657227dc44c6',null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;