begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-one-small-choice-luck-recruitment-refusal-two','/forum?thread=meta-one-small-choice&comment=live-one-small-choice-luck-recruitment-refusal-two','meta-one-small-choice','One tiny choice that would have changed everything'),
  ('post','live-worst-workplace-luck-laugh-food','/forum?thread=community-worst-workplace&comment=live-worst-workplace-luck-laugh-food','community-worst-workplace','Worst workplace in the realm: rank the departments'),
  ('raven','live-visenor-rhaella-kiss-luck-late-visenor','/ravens-eye?item=gallery-visenor-rhaella-kiss&comment=live-visenor-rhaella-kiss-luck-late-visenor',null,null),
  ('raven','live-jhaella-luck-would-impossible-ships','/ravens-eye?item=gallery-jhaella&comment=live-jhaella-luck-would-impossible-ships',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
