begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('raven','gallery-targaryens-in-essos-c01','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c01',null,null),
  ('raven','gallery-targaryens-in-essos-c02','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c02',null,null),
  ('raven','gallery-targaryens-in-essos-c03','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c03',null,null),
  ('raven','gallery-targaryens-in-essos-c04','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c04',null,null),
  ('raven','gallery-targaryens-in-essos-c05','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c05',null,null),
  ('raven','gallery-targaryens-in-essos-c06','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c06',null,null),
  ('raven','gallery-targaryens-in-essos-c07','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c07',null,null),
  ('raven','gallery-targaryens-in-essos-c08','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c08',null,null),
  ('raven','gallery-targaryens-in-essos-c09','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c09',null,null),
  ('raven','gallery-targaryens-in-essos-c10','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c10',null,null),
  ('raven','gallery-targaryens-in-essos-c11','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c11',null,null),
  ('raven','gallery-targaryens-in-essos-c12','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c12',null,null),
  ('raven','gallery-targaryens-in-essos-c13','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c13',null,null),
  ('raven','gallery-targaryens-in-essos-c14','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c14',null,null),
  ('raven','gallery-targaryens-in-essos-c15','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c15',null,null),
  ('raven','gallery-targaryens-in-essos-c16','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c16',null,null),
  ('raven','gallery-targaryens-in-essos-c17','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c17',null,null),
  ('raven','gallery-targaryens-in-essos-c18','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c18',null,null),
  ('raven','gallery-targaryens-in-essos-c19','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c19',null,null),
  ('raven','gallery-targaryens-in-essos-c20','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c20',null,null),
  ('raven','gallery-targaryens-in-essos-c21','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c21',null,null),
  ('raven','gallery-targaryens-in-essos-c22','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c22',null,null),
  ('raven','gallery-targaryens-in-essos-c23','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c23',null,null),
  ('raven','gallery-targaryens-in-essos-c24','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c24',null,null),
  ('raven','gallery-targaryens-in-essos-c25','/ravens-eye?item=gallery-targaryens-in-essos&comment=gallery-targaryens-in-essos-c25',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
