begin;

-- Server-authoritative online tables for The Great Game. The authoritative
-- state contains both private hands/decks and is therefore never selectable by
-- browser clients. Players receive a redacted projection through the API.
create table if not exists public.great_game_matches (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  host_id uuid not null references auth.users(id) on delete cascade,
  guest_id uuid references auth.users(id) on delete set null,
  host_deck jsonb not null default '[]'::jsonb,
  guest_deck jsonb,
  state jsonb,
  status text not null default 'waiting'
    check (status in ('waiting','active','finished','abandoned')),
  version integer not null default 0 check (version >= 0),
  winner_user_id uuid references auth.users(id) on delete set null,
  abandoned_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz,
  constraint great_game_code_format check (code ~ '^[A-Z0-9]{6}$'),
  constraint great_game_two_distinct_players check (guest_id is null or guest_id <> host_id)
);

create index if not exists great_game_matches_host_open_idx
  on public.great_game_matches(host_id, status, updated_at desc);
create index if not exists great_game_matches_guest_open_idx
  on public.great_game_matches(guest_id, status, updated_at desc)
  where guest_id is not null;

alter table public.great_game_matches enable row level security;
revoke all on table public.great_game_matches from anon, authenticated;

-- This helper is deliberately the only browser-visible way to ask whether the
-- current account belongs to a match. It does not expose state or deck JSON.
create or replace function public.is_great_game_participant(match_uuid uuid)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  select exists (
    select 1
    from public.great_game_matches m
    where m.id = match_uuid
      and auth.uid() is not null
      and (m.host_id = auth.uid() or m.guest_id = auth.uid())
  );
$$;
revoke all on function public.is_great_game_participant(uuid) from public;
grant execute on function public.is_great_game_participant(uuid) to authenticated;

-- Realtime emits only a tiny invalidation event. Clients then refetch their
-- own redacted state projection from /api/great-game.
create table if not exists public.great_game_events (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.great_game_matches(id) on delete cascade,
  version integer not null check (version >= 0),
  event_type text not null check (event_type in ('joined','state','left')),
  created_at timestamptz not null default now()
);

create index if not exists great_game_events_match_idx
  on public.great_game_events(match_id, id desc);

alter table public.great_game_events enable row level security;
revoke all on table public.great_game_events from anon;
grant select on table public.great_game_events to authenticated;

drop policy if exists great_game_events_participant_select on public.great_game_events;
create policy great_game_events_participant_select
  on public.great_game_events
  for select
  to authenticated
  using (public.is_great_game_participant(match_id));

-- Add the safe invalidation table to Supabase Realtime once.
do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'great_game_events'
  ) then
    execute 'alter publication supabase_realtime add table public.great_game_events';
  end if;
end $$;

notify pgrst,'reload schema';
commit;
