begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-hrrm-ama-rhaella-critic-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-rhaella-critic-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-visenor-dorne-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-visenor-dorne-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-edmyn-derrin-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-edmyn-derrin-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-smallfolk-bread-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-smallfolk-bread-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-players-gaelor-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-players-gaelor-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-jace-quality-jacejpeg-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-jace-quality-jacejpeg-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-alester-swordwife-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-alester-swordwife-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-lorenah-lemoncake-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-lorenah-lemoncake-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-queer-lavender-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-queer-lavender-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-children-pay-boneskin-correction-newt','/forum?thread=chapter-the-children-pay&comment=live-children-pay-boneskin-correction-newt','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-children-pay-vhaemys-advantage-jace','/forum?thread=chapter-the-children-pay&comment=live-children-pay-vhaemys-advantage-jace','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-rhaella-agency-village-correction-fic','/forum?thread=meta-rhaella-agency&comment=live-rhaella-agency-village-correction-fic','meta-rhaella-agency','Rhaella deserved a story of her own'),
  ('post','live-children-pay-ubeka-justice-critic','/forum?thread=chapter-the-children-pay&comment=live-children-pay-ubeka-justice-critic','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-hrrm-ama-tea-stannis-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-tea-stannis-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-misery-wellness-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-misery-wellness-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-sleep-poll-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-sleep-poll-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-delay-office-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-delay-office-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-hrrm-ama-rolls-dnd-followup','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-rolls-dnd-followup','c774865d-28f3-4cd5-abc0-657227dc44c6',null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
