begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-hrrm-ama-player-proud-jace','/forum?thread=c774865d-28f3-4cd5-abc0-657227dc44c6&comment=live-hrrm-ama-player-proud-jace','c774865d-28f3-4cd5-abc0-657227dc44c6',null),
  ('post','live-one-small-choice-carving-archive','/forum?thread=meta-one-small-choice&comment=live-one-small-choice-carving-archive','meta-one-small-choice','One tiny choice that would have changed everything'),
  ('post','live-one-small-choice-team-jace-refusal','/forum?thread=meta-one-small-choice&comment=live-one-small-choice-team-jace-refusal','meta-one-small-choice','One tiny choice that would have changed everything'),
  ('post','live-worst-workplace-vhaemys-food','/forum?thread=community-worst-workplace&comment=live-worst-workplace-vhaemys-food','community-worst-workplace','Worst workplace in the realm: rank the departments'),
  ('raven','live-eve-gitmem-greedy-visenor','/ravens-eye?item=gallery-visenor-eve-gitmem-gerek&comment=live-eve-gitmem-greedy-visenor',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
