begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('post','live-children-pay-luck-edmyn-finalgirl','/forum?thread=chapter-the-children-pay&comment=live-children-pay-luck-edmyn-finalgirl','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-ordinary-afternoon-luck-innkeepers-mert','/forum?thread=meta-one-ordinary-afternoon&comment=live-ordinary-afternoon-luck-innkeepers-mert','meta-one-ordinary-afternoon','One ordinary afternoon from a side character: who gets the page?'),
  ('post','live-children-pay-luck-rhaella-critic','/forum?thread=chapter-the-children-pay&comment=live-children-pay-luck-rhaella-critic','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-children-pay-luck-feeding-newt','/forum?thread=chapter-the-children-pay&comment=live-children-pay-luck-feeding-newt','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-children-pay-luck-renrose-objection','/forum?thread=chapter-the-children-pay&comment=live-children-pay-luck-renrose-objection','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-children-pay-luck-vhaemys-jace','/forum?thread=chapter-the-children-pay&comment=live-children-pay-luck-vhaemys-jace','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread'),
  ('post','live-children-pay-luck-dream-derrin','/forum?thread=chapter-the-children-pay&comment=live-children-pay-luck-dream-derrin','chapter-the-children-pay','Chapter XVII: The Children Pay — Discussion thread')
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
