begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('raven','gallery-baelenys-jace-kid-jacejpeg','/ravens-eye?item=gallery-baelenys-jace-kid&comment=gallery-baelenys-jace-kid-jacejpeg',null,null),
  ('raven','gallery-baelenys-jace-kid-archive','/ravens-eye?item=gallery-baelenys-jace-kid&comment=gallery-baelenys-jace-kid-archive',null,null),
  ('raven','gallery-baelenys-jace-kid-elder','/ravens-eye?item=gallery-baelenys-jace-kid&comment=gallery-baelenys-jace-kid-elder',null,null),
  ('raven','gallery-baelenys-jace-kid-critic','/ravens-eye?item=gallery-baelenys-jace-kid&comment=gallery-baelenys-jace-kid-critic',null,null),
  ('raven','gallery-baelenys-jace-kid-ada','/ravens-eye?item=gallery-baelenys-jace-kid&comment=gallery-baelenys-jace-kid-ada',null,null),
  ('raven','gallery-baelenys-jace-kid-jace','/ravens-eye?item=gallery-baelenys-jace-kid&comment=gallery-baelenys-jace-kid-jace',null,null),
  ('raven','gallery-baelenys-jace-kid-baelenys','/ravens-eye?item=gallery-baelenys-jace-kid&comment=gallery-baelenys-jace-kid-baelenys',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
