begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c01','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c01',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c02','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c02',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c03','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c03',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c04','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c04',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c05','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c05',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c06','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c06',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c07','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c07',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c08','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c08',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c09','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c09',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c10','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c10',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c11','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c11',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c12','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c12',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c13','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c13',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c14','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c14',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c15','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c15',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c16','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c16',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c17','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c17',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c18','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c18',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c19','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c19',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c20','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c20',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c21','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c21',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c22','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c22',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c23','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c23',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c24','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c24',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c25','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c25',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c26','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c26',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c27','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c27',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c28','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c28',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c29','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c29',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c30','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c30',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c31','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c31',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c32','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c32',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c33','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c33',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c34','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c34',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c35','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c35',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c36','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c36',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c37','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c37',null,null),
  ('raven','gallery-baelenys-jacaelon-hotel-lobby-c38','/ravens-eye?item=gallery-baelenys-jacaelon-hotel-lobby&comment=gallery-baelenys-jacaelon-hotel-lobby-c38',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
