begin;

-- Generated by npm run community:reactions. Preserve existing member reactions.
insert into public.community_reaction_targets (target_kind,target_id,href,thread_id,thread_title)
values
  ('raven','live-visenor-lap-only-happy-v','/ravens-eye?item=gallery-visenor-on-rhaellas-lap&comment=live-visenor-lap-only-happy-v',null,null)
on conflict (target_kind,target_id) do update set
  href=excluded.href, thread_id=excluded.thread_id, thread_title=excluded.thread_title;

commit;
